### PR TITLE
chore: add empty `prettier` config

### PR DESCRIPTION
**Pull request by G-Rath**
By not having a config file, `prettier` (really `cosmiconfig`) will look upwards and in home directories, which can result in linting errors if there is a config there (such as I have).

Adding an empty config file ensures that `prettier` will always use the right config.

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Review by bmish — APPROVED** [review]
Seems fine. Note that I'm using ESLint to run prettier currently (configured by eslint-plugin-square).

**Comment by G-Rath** [comment]
Yeah, this happens regardless of how `prettier` is invoked i.e. this is the result of me running `nrun lint:js` right now:

```
✖ 402 problems (402 errors, 0 warnings)
  402 errors and 0 warnings potentially fixable with the `--fix` option.
```

😅

**Comment by G-Rath** [comment]
@bmish so it seems that there is some contention between tools because you're actually at least using single-quotes in most of the codebase and that is what is being enforced by Prettier via ESLint, but not by the Prettier CLI (because it's not set in the config).

What I can't find out is where the Prettier plugin for ESLint is being configured to use single-quotes - all I can find is [this](https://github.com/square/eslint-plugin-square/blob/07c3e6fbe28e82a4b6d22979890d2ff1a6fb0015/lib/config/base.js#L77-L82), and even then that seems wrong because you [switched to double quotes](https://github.com/square/prettier-config/commit/735dc4b4c64fd782bca0cf945485f520dafa942a#diff-f15ca118c6708c0eac3d59e3a5245ff5984552b7c2400574556919a09bff15f5) a few months ago.

I think I missed this because of ESLint caching, which generally is considered broken due to this sort of thing. I'm happy to do a PR adding in the single quotes option which seems like the immediate right thing to do, but wanted to run that by you first since you've got a better understanding of all the configs :)

**Comment by bmish** [comment]
Prettier is being set to single quotes [here](https://github.com/square/eslint-plugin-square/blob/07c3e6fbe28e82a4b6d22979890d2ff1a6fb0015/lib/config/base.js#LL103). The goal is definitely to use single quotes and have eslint-plugin-square control that for us. It may have been a mistake for @square/prettier-config to switch to double quotes while the rest of eslint-plugin-square was intending to specify single quotes.

**Comment by G-Rath** [comment]
🤦 no idea how I missed that - I'd really recommend though having a prettier config at the project level, even if it's just pulling in `@square/prettier-config`, to avoid the original problem I described; but your call - if you don't want that then you should probably revert this.

fwiw my use-case is that I use `prettier` quite aggressively to format my code when I'm working, whereas ESLint has a higher overhead to run and typically is checking for more complex things that I might not be ready to address.

**Comment by bmish** [comment]
Fair points. I may rework this setup soon.

**Comment by bmish** [comment]
@G-Rath FYI https://github.com/bmish/eslint-doc-generator/pull/331 should fix the @square/prettier-config issue.

**Pull request merged**
