### PR TITLE
ci: drop node.js 14.x and 16.x testing

### PR DESCRIPTION
**Pull request by MikeMcC399**
- supports resolution of https://github.com/bmish/eslint-doc-generator/issues/529
- closes https://github.com/bmish/eslint-doc-generator/issues/535

## Issue

- Node.js `14.x` and `16.x` reached [Node.js End-of-life](https://github.com/nodejs/release#release-schedule) more than one year ago and so are unsupported by Node.js.
- To lint TypeScript in a flat configuration, a minimum [@typescript-eslint/eslint-plugin@7.0.0](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/) is required, which in turn requires Node.js `^18.18.0`. This rules out Node.js `14.x` and `16.x`.

## Change

- Remove `14.x` and `16.x` from the `node-version` matrix in [.github/workflows/ci.yml](https://github.com/bmish/eslint-doc-generator/blob/main/.github/workflows/ci.yml).

### CODE REVIEW

**Comment by ddzz** [comment]
We should remove 14 and 16 from the `engines` in the `package.json` as well.

**Comment by MikeMcC399** [comment]
@ddzz 

> We should remove 14 and 16 from the `engines` in the `package.json` as well.

It probably makes sense to close this PR and to open a new one which removes 14 and 16 from CI and from engines in one coordinated PR. I can do that if you want. I would align the prerequisites with ESLint v9 in that case.

**Comment by MikeMcC399** [comment]
I was originally planning to delay modifying engines until the repo is compatible with ESLint v9, then change the prerequisites of eslint and engines together. I guess the order does not matter too much so long as no new version is released. This would be a breaking change anyway.

**Comment by ddzz** [comment]
@bmish is MIA so I'll approve and merge this. We should add Node 20.x to the matrix in another PR. Thanks for all your work in this repo!

**Review by ddzz — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@ddzz 

> @bmish is MIA so I'll approve and merge this. We should add Node 20.x to the matrix in another PR. Thanks for all your work in this repo!

Thank you! This makes it cleaner for the follow-on PRs. I'm happy to work on this knowing you are there to review and merge. 🙂 I don't think we need @bmish at this time. He may still be traveling.

**Comment by MikeMcC399** [comment]
@ddzz 

> We should add Node 20.x to the matrix in another PR. 

Agreed, however the workflow is not yet compatible with Node.js >= 20 (otherwise I would have already added it). I am however planning to tackle this.

**Pull request merged**
